modLoader="javafml"
loaderVersion="[46,)"
license="CC0"
issueTrackerURL="https://github.com/dhyces/bad-eyes/issues/"
[[mods]]
modId="badeyes"
version="${file.jarVersion}"
displayName="Bad Eyes"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bad-eyes/"
logoFile="logo.png"
authors="dhyces"
description='''Near-sighted simulator'''

[[dependencies.badeyes]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"
[[dependencies.badeyes]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
